""" Constants file for Auth0's seed project
"""
CLIENT_ID = 'CLIENT_ID'
CLIENT_SECRET = 'CLIENT_SECRET'
CALLBACK_URL = 'CALLBACK_URL'
BASE_URL = 'BASE_URL'
AUTH_URL = 'AUTH_URL'
TOKEN_URL = 'TOKEN_URL'
LOGOUT_URL = 'LOGOUT_URL'
AUDIENCE = 'AUDIENCE'
PROFILE_KEY = 'profile'
SECRET_KEY = 'ThisIsTheSecretKey'
JWT_PAYLOAD = 'jwt_payload'

