""" Constants file for Auth0's seed project
"""
CLIENT_ID = 'CLIENT_ID'
CLIENT_SECRET = 'CLIENT_SECRET'
CALLBACK_URL = 'CALLBACK_URL'
BASE_URL = 'BASE_URL'
AUTH_SUFFIX = 'AUTH_SUFFIX'
TOKEN_SUFFIX = 'TOKEN_SUFFIX'
LOGOUT_SUFFIX = 'LOGOUT_SUFFIX'
AUDIENCE = 'AUDIENCE'
PROFILE_KEY = 'profile'
SECRET_KEY = 'ThisIsTheSecretKey'
JWT_PAYLOAD = 'jwt_payload'

